add: implement posts command and improve post series result

diff --git a/bin/bsky b/bin/bsky
--- a/bin/bsky
+++ b/bin/bsky
@@ -17,6 +17,7 @@ BSKYSHCLI_CLI_VERSION='0.4.0'
 # global option (default value)
 BSKYSHCLI_POST_DEFAULT_LANGUAGES=''
 BSKYSHCLI_POST_VIA='ON'
+BSKYSHCLI_PATH_DELIMITER=':'
 BSKYSHCLI_GLOBAL_OPTION_PROFILE=''
 
 # $<variables> want to pass through for jq
@@ -158,6 +159,7 @@ commands:
   feed         show custom feed (feed generator).
   author-feed  show author feed.
   post         post text.
+  posts        multiple text posts.
   reply        reply to existing post.
   repost       reopst of existing post.
   quote        post by quoting an existing post.
@@ -385,6 +387,42 @@ note:
 EOS
 
   debug 'output_help_post' 'END'
+}
+
+output_help_posts()
+{
+  debug 'output_help_posts' 'START'
+
+  cat << 'EOS'
+bsky post help
+
+usage: bsky posts [--mode <posts mode>] [--text '<text>'] [--text-files '<file path>[:...]'] [--langs '<language code>[,...]']
+
+parameters:
+  --mode <posts mode>
+    Specify the relationship between multiple texts.
+    posts mode:
+      thread (default)
+      sibling
+      independence
+
+  --text '<text>'
+    Specify text for post.
+
+  --text-files '<file path>[:...]'
+    Specify the path of text files to post.
+    Separate multiple path of text files with colons (e.g. --text-files '/path/to/a.txt:/path/to/b.txt').
+
+  --langs '<language code>[,...]'
+    Specify the languages to include in the posts.
+    Separate multiple language codes with commas (e.g. --langs 'en,ja').
+
+note:
+  you must have started a Bluesky session with the login command.
+  Either --text or --text-files must be specified.
+EOS
+
+  debug 'output_help_posts' 'END'
 }
 
 output_help_reply()
@@ -1167,6 +1205,56 @@ command_post()
   debug 'command_post' 'END'
 }
 
+command_posts()
+{
+  debug 'command_posts' 'START'
+
+  if [ "$1" = 'help' ]
+  then
+    output_help_posts
+  else
+    parse_parameters '--mode:1 --text:1 --text-files:1 --langs:1' "$@"
+
+    if [ -z "${PARSED_PARAM_KEYVALUE_text}" ] && [ -z "${PARSED_PARAM_KEYVALUE_text_files}" ]
+    then
+      error 'parameter specify required --text or --text-files'
+    fi
+
+    if [ -n "${PARSED_PARAM_KEYVALUE_mode}" ]
+    then
+      # dynamic assignment in parse_parameters
+      # shellcheck disable=SC2154
+      case $PARSED_PARAM_KEYVALUE_mode in
+        thread|sibling|independence)
+          ;;
+        *)
+          error "--mode value ${PARSED_PARAM_KEYVALUE_mode} is not found. see 'bsky posts help'"
+          ;;
+      esac
+    fi
+
+    # posts count check
+    posts_count=0
+    if [ -n "${PARSED_PARAM_KEYVALUE_text}" ]
+    then
+      posts_count=1
+    fi
+    _slice "${PARSED_PARAM_KEYVALUE_text_files}" "${BSKYSHCLI_PATH_DELIMITER}"
+    test_files_count=$?
+    posts_count=`expr "${posts_count}" + "${test_files_count}"`
+    if [ "${posts_count}" -gt 10 ]
+    then
+      error "The total number of posts by --text and --text-files options exceeds the limit of 10. Detect count:${posts_count}"
+    fi
+
+    # dynamic assignment in parse_parameters
+    # shellcheck disable=SC2154
+    core_posts "${PARSED_PARAM_KEYVALUE_mode}" "${PARSED_PARAM_KEYVALUE_text}" "${PARSED_PARAM_KEYVALUE_text_files}" "${PARSED_PARAM_KEYVALUE_langs}"
+  fi
+
+  debug 'command_posts' 'END'
+}
+
 command_reply()
 {
   debug 'command_reply' 'START'
@@ -1674,6 +1762,10 @@ case $1 in
   post)
     shift
     command_post "$@"
+    ;;
+  posts)
+    shift
+    command_posts "$@"
     ;;
   reply)
     shift
